AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create an S3 bucket for Lambda function code'

Parameters:
  ProjectTagValue:
    Description: 'Value of the "project" tag'
    Type: 'String'
    Default: 'imaginary-map'

Resources:
  CodeRepository:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      Tags:
        - Key: 'project'
          Value: !Ref ProjectTagValue

Outputs:
  CodeRepositoryName:
    Description: 'Name of the S3 bucket for Lambda function code'
    Value: !Ref CodeRepository
