name: 'Runs tests on pull request'
on: 'push' # for tests only
#  pull_request:
#    branches:
#      - 'master'

jobs:
  build:
    name: 'Build and test the Go module'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        go-version:
          - '1.13'
          - '1.14'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Setup go'
        uses: 'actions/setup-go@v2'
        with:
          go-version: ${{ matrix.go-version }}
      - run: 'go version'
      - name: 'Test all packages'
        run: 'go test -v ./...'
      # builds Lambda functions
      - name: 'build get-islands-tile'
        run: 'go build'
        working-directory: './cdn/api/get-islands-tile'
      - name: 'build get-papers-tile'
        run: 'go build'
        working-directory: './cdn/api/get-papers-tile'
